import type { Metadata } from "next";
import "./globals.css";
import DarkModeToggle from "@/components/DarkModeToggle";
import ThemeProvider from "@/app/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans antialiased transition-colors duration-300 dark:text-white bg-white dark:bg-black">
        <ThemeProvider>
          {children}
          <DarkModeToggle />
        </ThemeProvider>
      </body>
    </html>
  );
}
