import type { Project } from "@/types/content";

export const projects: Project[] = [
  {
    title: "Inpeak",
    summary: "개발자를 위한 모의면접 웹 서비스",
    role: "Frontend",
    focus: "면접 연습 플로우와 사용자 피드백 경험 설계",
    github: "https://github.com/Paicearea/Inpeak-frontend",
    deploy: "https://inpeak.kr",
    tags: [
      "React",
      "TypeScript",
      "Recoil",
      "Axios",
      "Styled-components",
      "Vite",
      "Lottie-react",
      "date-fns",
    ],
    featured: true,
  },
  {
    title: "Paicearea",
    summary: "개인 프로필 제작 프로젝트",
    role: "Frontend / Design",
    focus: "Next.js 기반 포트폴리오 정보 구조와 다크 모드 구현",
    github: "https://github.com/Paicearea/Paicearea",
    deploy: "https://www.paicearea.site",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "MDX", "RSS Parser"],
    featured: true,
  },
  {
    title: "Promfren",
    summary: "유용한 프롬프트 제공 및 작성 가이드 제공 웹 서비스",
    role: "Frontend",
    focus: "탐색과 작성 흐름을 연결하는 프롬프트 UI 구성",
    github: "https://github.com/Paicearea/Promfren-front",
    deploy: "https://2024-ll-hackathon.github.io/promfren_front",
    tags: ["React", "TypeScript", "Redux-Toolkit", "Styled-Components", "Axios"],
  },
  {
    title: "앤딩",
    summary: "여러 유저들과 소설을 협업 창작하는 React Native 앱 서비스",
    role: "Mobile Frontend",
    focus: "협업 창작 경험을 위한 모바일 화면 흐름 구현",
    github: "https://github.com/Paicearea/Ending",
    tags: [
      "React Native",
      "TypeScript",
      "Redux-Toolkit",
      "Styled-Components",
      "React-Hook-Form",
    ],
  },
  {
    title: "이투",
    summary: "중장년층에게 게이미피케이션 요소를 적용한 구인구직 웹앱 서비스",
    role: "Frontend",
    focus: "참여 동기를 높이는 구직 서비스 화면 구성",
    github: "https://github.com/Paicearea/E2-front",
    deploy: "https://k-html-today.github.io/Front/",
    tags: [
      "React",
      "TypeScript",
      "Redux-Toolkit",
      "Styled-Components",
      "Axios",
      "React-Hook-Form",
    ],
  },
  {
    title: "모잉",
    summary: "산모와 보호자를 연결해주는 웹 서비스",
    role: "Frontend",
    focus: "민감한 사용자 여정을 고려한 정보 전달 화면 구현",
    github: "https://github.com/Paicearea/Moing",
    tags: ["React", "TypeScript", "Emotion", "Chart.js", "Axios"],
  },
];
